return {
   "m4xshen/hardtime.nvim",
   lazy = false,
   dependencies = { "MunifTanjim/nui.nvim" },
   opts = {
     max_count = 7,
     disable_mouse = false,
     disabled_filetypes = {
          ["aerial"] = true,
          ["alpha"] = true,
          ["Avante"] = true,
          ["checkhealth"] = true,
          ["dapui.*"] = true,
          ["db.*"] = true,
          ["Diffview.*"] = true,
          ["Dressing.*"] = true,
          ["fugitive"] = true,
          ["help"] = true,
          ["httpResult"] = true,
          ["lazy"] = true,
          ["lspinfo"] = true,
          ["mason"] = true,
          ["minifiles"] = true,
          ["Neogit.*"] = true,
          ["neo%-tree.*"] = true,
          ["neotest%-summary"] = true,
          ["netrw"] = true,
          ["noice"] = true,
          ["notify"] = true,
          ["NvimTree"] = true,
          ["oil"] = true,
          ["prompt"] = true,
          ["qf"] = true,
          ["query"] = true,
          ["snacks_dashboard"] = true,
          ["TelescopePrompt"] = true,
          ["Trouble"] = true,
          ["trouble"] = true,
          ["VoltWindow"] = true,
          ["undotree"] = true,
          ["harpoon"] = true,

       },
   },
}
